import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#326943",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e6e3d0",
        surface: "#fdfae6",
        "on-background": "#1c1c11",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#02210f",
        "secondary-container": "#c5e9cb",
        "surface-bright": "#fdfae6",
        "inverse-surface": "#313124",
        "primary-fixed": "#b4f1c0",
        "on-secondary-fixed-variant": "#2f4d37",
        "surface-container-low": "#f7f4e1",
        "on-surface-variant": "#414941",
        "surface-dim": "#dddbc8",
        "outline-variant": "#c0c9be",
        tertiary: "#8d4a58",
        "secondary-fixed": "#c8ebcd",
        "primary-fixed-dim": "#99d4a5",
        "on-error": "#ffffff",
        "tertiary-container": "#ffaaba",
        "on-secondary-container": "#4a6a52",
        "on-primary-fixed": "#00210c",
        background: "#fdfae6",
        outline: "#717970",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#accfb2",
        "on-tertiary-fixed-variant": "#713341",
        "inverse-on-surface": "#f4f1de",
        "on-error-container": "#93000a",
        secondary: "#46654e",
        "surface-container": "#f1eedb",
        "tertiary-fixed-dim": "#ffb1c0",
        "surface-variant": "#e6e3d0",
        primary: "#326943",
        "error-container": "#ffdad6",
        "primary-container": "#94cfa0",
        "on-primary-fixed-variant": "#18512d",
        "inverse-primary": "#99d4a5",
        "on-surface": "#1c1c11",
        "tertiary-fixed": "#ffd9de",
        "on-tertiary-fixed": "#3a0717",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#215934",
        "surface-container-high": "#ebe9d6",
        "on-tertiary-container": "#7b3b4a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-manrope)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-inter)"],
      },
      boxShadow: {
        editorial: "0 12px 40px -5px rgba(28, 28, 17, 0.05)",
      },
      tracking: {
        editorial: "0.2em",
      },
    },
  },
  plugins: [],
};

export default config;
